// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module AXIM2Mat (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_fb_AWVALID,
        m_axi_fb_AWREADY,
        m_axi_fb_AWADDR,
        m_axi_fb_AWID,
        m_axi_fb_AWLEN,
        m_axi_fb_AWSIZE,
        m_axi_fb_AWBURST,
        m_axi_fb_AWLOCK,
        m_axi_fb_AWCACHE,
        m_axi_fb_AWPROT,
        m_axi_fb_AWQOS,
        m_axi_fb_AWREGION,
        m_axi_fb_AWUSER,
        m_axi_fb_WVALID,
        m_axi_fb_WREADY,
        m_axi_fb_WDATA,
        m_axi_fb_WSTRB,
        m_axi_fb_WLAST,
        m_axi_fb_WID,
        m_axi_fb_WUSER,
        m_axi_fb_ARVALID,
        m_axi_fb_ARREADY,
        m_axi_fb_ARADDR,
        m_axi_fb_ARID,
        m_axi_fb_ARLEN,
        m_axi_fb_ARSIZE,
        m_axi_fb_ARBURST,
        m_axi_fb_ARLOCK,
        m_axi_fb_ARCACHE,
        m_axi_fb_ARPROT,
        m_axi_fb_ARQOS,
        m_axi_fb_ARREGION,
        m_axi_fb_ARUSER,
        m_axi_fb_RVALID,
        m_axi_fb_RREADY,
        m_axi_fb_RDATA,
        m_axi_fb_RLAST,
        m_axi_fb_RID,
        m_axi_fb_RUSER,
        m_axi_fb_RRESP,
        m_axi_fb_BVALID,
        m_axi_fb_BREADY,
        m_axi_fb_BRESP,
        m_axi_fb_BID,
        m_axi_fb_BUSER,
        fb_offset_dout,
        fb_offset_empty_n,
        fb_offset_read,
        img_rows_V_dout,
        img_rows_V_empty_n,
        img_rows_V_read,
        img_cols_V_dout,
        img_cols_V_empty_n,
        img_cols_V_read,
        img_data_stream_V_din,
        img_data_stream_V_full_n,
        img_data_stream_V_write,
        img_rows_V_out_din,
        img_rows_V_out_full_n,
        img_rows_V_out_write,
        img_cols_V_out_din,
        img_cols_V_out_full_n,
        img_cols_V_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_fb_AWVALID;
input   m_axi_fb_AWREADY;
output  [31:0] m_axi_fb_AWADDR;
output  [0:0] m_axi_fb_AWID;
output  [31:0] m_axi_fb_AWLEN;
output  [2:0] m_axi_fb_AWSIZE;
output  [1:0] m_axi_fb_AWBURST;
output  [1:0] m_axi_fb_AWLOCK;
output  [3:0] m_axi_fb_AWCACHE;
output  [2:0] m_axi_fb_AWPROT;
output  [3:0] m_axi_fb_AWQOS;
output  [3:0] m_axi_fb_AWREGION;
output  [0:0] m_axi_fb_AWUSER;
output   m_axi_fb_WVALID;
input   m_axi_fb_WREADY;
output  [7:0] m_axi_fb_WDATA;
output  [0:0] m_axi_fb_WSTRB;
output   m_axi_fb_WLAST;
output  [0:0] m_axi_fb_WID;
output  [0:0] m_axi_fb_WUSER;
output   m_axi_fb_ARVALID;
input   m_axi_fb_ARREADY;
output  [31:0] m_axi_fb_ARADDR;
output  [0:0] m_axi_fb_ARID;
output  [31:0] m_axi_fb_ARLEN;
output  [2:0] m_axi_fb_ARSIZE;
output  [1:0] m_axi_fb_ARBURST;
output  [1:0] m_axi_fb_ARLOCK;
output  [3:0] m_axi_fb_ARCACHE;
output  [2:0] m_axi_fb_ARPROT;
output  [3:0] m_axi_fb_ARQOS;
output  [3:0] m_axi_fb_ARREGION;
output  [0:0] m_axi_fb_ARUSER;
input   m_axi_fb_RVALID;
output   m_axi_fb_RREADY;
input  [7:0] m_axi_fb_RDATA;
input   m_axi_fb_RLAST;
input  [0:0] m_axi_fb_RID;
input  [0:0] m_axi_fb_RUSER;
input  [1:0] m_axi_fb_RRESP;
input   m_axi_fb_BVALID;
output   m_axi_fb_BREADY;
input  [1:0] m_axi_fb_BRESP;
input  [0:0] m_axi_fb_BID;
input  [0:0] m_axi_fb_BUSER;
input  [31:0] fb_offset_dout;
input   fb_offset_empty_n;
output   fb_offset_read;
input  [11:0] img_rows_V_dout;
input   img_rows_V_empty_n;
output   img_rows_V_read;
input  [11:0] img_cols_V_dout;
input   img_cols_V_empty_n;
output   img_cols_V_read;
output  [7:0] img_data_stream_V_din;
input   img_data_stream_V_full_n;
output   img_data_stream_V_write;
output  [11:0] img_rows_V_out_din;
input   img_rows_V_out_full_n;
output   img_rows_V_out_write;
output  [11:0] img_cols_V_out_din;
input   img_cols_V_out_full_n;
output   img_cols_V_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_fb_ARVALID;
reg m_axi_fb_RREADY;
reg fb_offset_read;
reg img_rows_V_read;
reg img_cols_V_read;
reg img_data_stream_V_write;
reg img_rows_V_out_write;
reg img_cols_V_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    fb_offset_blk_n;
reg    img_rows_V_blk_n;
reg    img_cols_V_blk_n;
reg    img_rows_V_out_blk_n;
reg    img_cols_V_out_blk_n;
reg   [31:0] fb_offset_read_reg_154;
reg    ap_block_state1;
reg   [11:0] img_rows_V_read_reg_159;
reg   [11:0] img_cols_V_read_reg_164;
wire    grp_Array2Mat_fu_140_ap_start;
wire    grp_Array2Mat_fu_140_ap_done;
wire    grp_Array2Mat_fu_140_ap_idle;
wire    grp_Array2Mat_fu_140_ap_ready;
wire    grp_Array2Mat_fu_140_m_axi_fb_AWVALID;
wire   [31:0] grp_Array2Mat_fu_140_m_axi_fb_AWADDR;
wire   [0:0] grp_Array2Mat_fu_140_m_axi_fb_AWID;
wire   [31:0] grp_Array2Mat_fu_140_m_axi_fb_AWLEN;
wire   [2:0] grp_Array2Mat_fu_140_m_axi_fb_AWSIZE;
wire   [1:0] grp_Array2Mat_fu_140_m_axi_fb_AWBURST;
wire   [1:0] grp_Array2Mat_fu_140_m_axi_fb_AWLOCK;
wire   [3:0] grp_Array2Mat_fu_140_m_axi_fb_AWCACHE;
wire   [2:0] grp_Array2Mat_fu_140_m_axi_fb_AWPROT;
wire   [3:0] grp_Array2Mat_fu_140_m_axi_fb_AWQOS;
wire   [3:0] grp_Array2Mat_fu_140_m_axi_fb_AWREGION;
wire   [0:0] grp_Array2Mat_fu_140_m_axi_fb_AWUSER;
wire    grp_Array2Mat_fu_140_m_axi_fb_WVALID;
wire   [7:0] grp_Array2Mat_fu_140_m_axi_fb_WDATA;
wire   [0:0] grp_Array2Mat_fu_140_m_axi_fb_WSTRB;
wire    grp_Array2Mat_fu_140_m_axi_fb_WLAST;
wire   [0:0] grp_Array2Mat_fu_140_m_axi_fb_WID;
wire   [0:0] grp_Array2Mat_fu_140_m_axi_fb_WUSER;
wire    grp_Array2Mat_fu_140_m_axi_fb_ARVALID;
wire   [31:0] grp_Array2Mat_fu_140_m_axi_fb_ARADDR;
wire   [0:0] grp_Array2Mat_fu_140_m_axi_fb_ARID;
wire   [31:0] grp_Array2Mat_fu_140_m_axi_fb_ARLEN;
wire   [2:0] grp_Array2Mat_fu_140_m_axi_fb_ARSIZE;
wire   [1:0] grp_Array2Mat_fu_140_m_axi_fb_ARBURST;
wire   [1:0] grp_Array2Mat_fu_140_m_axi_fb_ARLOCK;
wire   [3:0] grp_Array2Mat_fu_140_m_axi_fb_ARCACHE;
wire   [2:0] grp_Array2Mat_fu_140_m_axi_fb_ARPROT;
wire   [3:0] grp_Array2Mat_fu_140_m_axi_fb_ARQOS;
wire   [3:0] grp_Array2Mat_fu_140_m_axi_fb_ARREGION;
wire   [0:0] grp_Array2Mat_fu_140_m_axi_fb_ARUSER;
wire    grp_Array2Mat_fu_140_m_axi_fb_RREADY;
wire    grp_Array2Mat_fu_140_m_axi_fb_BREADY;
wire   [7:0] grp_Array2Mat_fu_140_img_data_stream_V_din;
wire    grp_Array2Mat_fu_140_img_data_stream_V_write;
reg    grp_Array2Mat_fu_140_ap_start_reg;
reg    ap_block_state1_ignore_call20;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_Array2Mat_fu_140_ap_start_reg = 1'b0;
end

Array2Mat grp_Array2Mat_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Array2Mat_fu_140_ap_start),
    .ap_done(grp_Array2Mat_fu_140_ap_done),
    .ap_idle(grp_Array2Mat_fu_140_ap_idle),
    .ap_ready(grp_Array2Mat_fu_140_ap_ready),
    .m_axi_fb_AWVALID(grp_Array2Mat_fu_140_m_axi_fb_AWVALID),
    .m_axi_fb_AWREADY(1'b0),
    .m_axi_fb_AWADDR(grp_Array2Mat_fu_140_m_axi_fb_AWADDR),
    .m_axi_fb_AWID(grp_Array2Mat_fu_140_m_axi_fb_AWID),
    .m_axi_fb_AWLEN(grp_Array2Mat_fu_140_m_axi_fb_AWLEN),
    .m_axi_fb_AWSIZE(grp_Array2Mat_fu_140_m_axi_fb_AWSIZE),
    .m_axi_fb_AWBURST(grp_Array2Mat_fu_140_m_axi_fb_AWBURST),
    .m_axi_fb_AWLOCK(grp_Array2Mat_fu_140_m_axi_fb_AWLOCK),
    .m_axi_fb_AWCACHE(grp_Array2Mat_fu_140_m_axi_fb_AWCACHE),
    .m_axi_fb_AWPROT(grp_Array2Mat_fu_140_m_axi_fb_AWPROT),
    .m_axi_fb_AWQOS(grp_Array2Mat_fu_140_m_axi_fb_AWQOS),
    .m_axi_fb_AWREGION(grp_Array2Mat_fu_140_m_axi_fb_AWREGION),
    .m_axi_fb_AWUSER(grp_Array2Mat_fu_140_m_axi_fb_AWUSER),
    .m_axi_fb_WVALID(grp_Array2Mat_fu_140_m_axi_fb_WVALID),
    .m_axi_fb_WREADY(1'b0),
    .m_axi_fb_WDATA(grp_Array2Mat_fu_140_m_axi_fb_WDATA),
    .m_axi_fb_WSTRB(grp_Array2Mat_fu_140_m_axi_fb_WSTRB),
    .m_axi_fb_WLAST(grp_Array2Mat_fu_140_m_axi_fb_WLAST),
    .m_axi_fb_WID(grp_Array2Mat_fu_140_m_axi_fb_WID),
    .m_axi_fb_WUSER(grp_Array2Mat_fu_140_m_axi_fb_WUSER),
    .m_axi_fb_ARVALID(grp_Array2Mat_fu_140_m_axi_fb_ARVALID),
    .m_axi_fb_ARREADY(m_axi_fb_ARREADY),
    .m_axi_fb_ARADDR(grp_Array2Mat_fu_140_m_axi_fb_ARADDR),
    .m_axi_fb_ARID(grp_Array2Mat_fu_140_m_axi_fb_ARID),
    .m_axi_fb_ARLEN(grp_Array2Mat_fu_140_m_axi_fb_ARLEN),
    .m_axi_fb_ARSIZE(grp_Array2Mat_fu_140_m_axi_fb_ARSIZE),
    .m_axi_fb_ARBURST(grp_Array2Mat_fu_140_m_axi_fb_ARBURST),
    .m_axi_fb_ARLOCK(grp_Array2Mat_fu_140_m_axi_fb_ARLOCK),
    .m_axi_fb_ARCACHE(grp_Array2Mat_fu_140_m_axi_fb_ARCACHE),
    .m_axi_fb_ARPROT(grp_Array2Mat_fu_140_m_axi_fb_ARPROT),
    .m_axi_fb_ARQOS(grp_Array2Mat_fu_140_m_axi_fb_ARQOS),
    .m_axi_fb_ARREGION(grp_Array2Mat_fu_140_m_axi_fb_ARREGION),
    .m_axi_fb_ARUSER(grp_Array2Mat_fu_140_m_axi_fb_ARUSER),
    .m_axi_fb_RVALID(m_axi_fb_RVALID),
    .m_axi_fb_RREADY(grp_Array2Mat_fu_140_m_axi_fb_RREADY),
    .m_axi_fb_RDATA(m_axi_fb_RDATA),
    .m_axi_fb_RLAST(m_axi_fb_RLAST),
    .m_axi_fb_RID(m_axi_fb_RID),
    .m_axi_fb_RUSER(m_axi_fb_RUSER),
    .m_axi_fb_RRESP(m_axi_fb_RRESP),
    .m_axi_fb_BVALID(1'b0),
    .m_axi_fb_BREADY(grp_Array2Mat_fu_140_m_axi_fb_BREADY),
    .m_axi_fb_BRESP(2'd0),
    .m_axi_fb_BID(1'd0),
    .m_axi_fb_BUSER(1'd0),
    .fb_offset(fb_offset_read_reg_154),
    .img_rows_V_read(img_rows_V_read_reg_159),
    .img_cols_V_read(img_cols_V_read_reg_164),
    .img_data_stream_V_din(grp_Array2Mat_fu_140_img_data_stream_V_din),
    .img_data_stream_V_full_n(img_data_stream_V_full_n),
    .img_data_stream_V_write(grp_Array2Mat_fu_140_img_data_stream_V_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (grp_Array2Mat_fu_140_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Array2Mat_fu_140_ap_start_reg <= 1'b0;
    end else begin
        if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Array2Mat_fu_140_ap_start_reg <= 1'b1;
        end else if ((grp_Array2Mat_fu_140_ap_ready == 1'b1)) begin
            grp_Array2Mat_fu_140_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        fb_offset_read_reg_154 <= fb_offset_dout;
        img_cols_V_read_reg_164 <= img_cols_V_dout;
        img_rows_V_read_reg_159 <= img_rows_V_dout;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_Array2Mat_fu_140_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        fb_offset_blk_n = fb_offset_empty_n;
    end else begin
        fb_offset_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        fb_offset_read = 1'b1;
    end else begin
        fb_offset_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_blk_n = img_cols_V_empty_n;
    end else begin
        img_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_out_blk_n = img_cols_V_out_full_n;
    end else begin
        img_cols_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_out_write = 1'b1;
    end else begin
        img_cols_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_cols_V_read = 1'b1;
    end else begin
        img_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_data_stream_V_write = grp_Array2Mat_fu_140_img_data_stream_V_write;
    end else begin
        img_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_blk_n = img_rows_V_empty_n;
    end else begin
        img_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_out_blk_n = img_rows_V_out_full_n;
    end else begin
        img_rows_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_out_write = 1'b1;
    end else begin
        img_rows_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_rows_V_read = 1'b1;
    end else begin
        img_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_Array2Mat_fu_140_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_fb_ARVALID = grp_Array2Mat_fu_140_m_axi_fb_ARVALID;
    end else begin
        m_axi_fb_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_fb_RREADY = grp_Array2Mat_fu_140_m_axi_fb_RREADY;
    end else begin
        m_axi_fb_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_Array2Mat_fu_140_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call20 = ((fb_offset_empty_n == 1'b0) | (real_start == 1'b0) | (img_cols_V_out_full_n == 1'b0) | (img_rows_V_out_full_n == 1'b0) | (img_cols_V_empty_n == 1'b0) | (img_rows_V_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_Array2Mat_fu_140_ap_start = grp_Array2Mat_fu_140_ap_start_reg;

assign img_cols_V_out_din = img_cols_V_dout;

assign img_data_stream_V_din = grp_Array2Mat_fu_140_img_data_stream_V_din;

assign img_rows_V_out_din = img_rows_V_dout;

assign m_axi_fb_ARADDR = grp_Array2Mat_fu_140_m_axi_fb_ARADDR;

assign m_axi_fb_ARBURST = grp_Array2Mat_fu_140_m_axi_fb_ARBURST;

assign m_axi_fb_ARCACHE = grp_Array2Mat_fu_140_m_axi_fb_ARCACHE;

assign m_axi_fb_ARID = grp_Array2Mat_fu_140_m_axi_fb_ARID;

assign m_axi_fb_ARLEN = grp_Array2Mat_fu_140_m_axi_fb_ARLEN;

assign m_axi_fb_ARLOCK = grp_Array2Mat_fu_140_m_axi_fb_ARLOCK;

assign m_axi_fb_ARPROT = grp_Array2Mat_fu_140_m_axi_fb_ARPROT;

assign m_axi_fb_ARQOS = grp_Array2Mat_fu_140_m_axi_fb_ARQOS;

assign m_axi_fb_ARREGION = grp_Array2Mat_fu_140_m_axi_fb_ARREGION;

assign m_axi_fb_ARSIZE = grp_Array2Mat_fu_140_m_axi_fb_ARSIZE;

assign m_axi_fb_ARUSER = grp_Array2Mat_fu_140_m_axi_fb_ARUSER;

assign m_axi_fb_AWADDR = 32'd0;

assign m_axi_fb_AWBURST = 2'd0;

assign m_axi_fb_AWCACHE = 4'd0;

assign m_axi_fb_AWID = 1'd0;

assign m_axi_fb_AWLEN = 32'd0;

assign m_axi_fb_AWLOCK = 2'd0;

assign m_axi_fb_AWPROT = 3'd0;

assign m_axi_fb_AWQOS = 4'd0;

assign m_axi_fb_AWREGION = 4'd0;

assign m_axi_fb_AWSIZE = 3'd0;

assign m_axi_fb_AWUSER = 1'd0;

assign m_axi_fb_AWVALID = 1'b0;

assign m_axi_fb_BREADY = 1'b0;

assign m_axi_fb_WDATA = 8'd0;

assign m_axi_fb_WID = 1'd0;

assign m_axi_fb_WLAST = 1'b0;

assign m_axi_fb_WSTRB = 1'd0;

assign m_axi_fb_WUSER = 1'd0;

assign m_axi_fb_WVALID = 1'b0;

assign start_out = real_start;

endmodule //AXIM2Mat
