// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Mat2Array_HH_
#define _Mat2Array_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Mat2Array : public sc_module {
    // Port declarations 55
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > img_data_stream_V_dout;
    sc_in< sc_logic > img_data_stream_V_empty_n;
    sc_out< sc_logic > img_data_stream_V_read;
    sc_out< sc_logic > m_axi_fb_AWVALID;
    sc_in< sc_logic > m_axi_fb_AWREADY;
    sc_out< sc_lv<32> > m_axi_fb_AWADDR;
    sc_out< sc_lv<1> > m_axi_fb_AWID;
    sc_out< sc_lv<32> > m_axi_fb_AWLEN;
    sc_out< sc_lv<3> > m_axi_fb_AWSIZE;
    sc_out< sc_lv<2> > m_axi_fb_AWBURST;
    sc_out< sc_lv<2> > m_axi_fb_AWLOCK;
    sc_out< sc_lv<4> > m_axi_fb_AWCACHE;
    sc_out< sc_lv<3> > m_axi_fb_AWPROT;
    sc_out< sc_lv<4> > m_axi_fb_AWQOS;
    sc_out< sc_lv<4> > m_axi_fb_AWREGION;
    sc_out< sc_lv<1> > m_axi_fb_AWUSER;
    sc_out< sc_logic > m_axi_fb_WVALID;
    sc_in< sc_logic > m_axi_fb_WREADY;
    sc_out< sc_lv<8> > m_axi_fb_WDATA;
    sc_out< sc_lv<1> > m_axi_fb_WSTRB;
    sc_out< sc_logic > m_axi_fb_WLAST;
    sc_out< sc_lv<1> > m_axi_fb_WID;
    sc_out< sc_lv<1> > m_axi_fb_WUSER;
    sc_out< sc_logic > m_axi_fb_ARVALID;
    sc_in< sc_logic > m_axi_fb_ARREADY;
    sc_out< sc_lv<32> > m_axi_fb_ARADDR;
    sc_out< sc_lv<1> > m_axi_fb_ARID;
    sc_out< sc_lv<32> > m_axi_fb_ARLEN;
    sc_out< sc_lv<3> > m_axi_fb_ARSIZE;
    sc_out< sc_lv<2> > m_axi_fb_ARBURST;
    sc_out< sc_lv<2> > m_axi_fb_ARLOCK;
    sc_out< sc_lv<4> > m_axi_fb_ARCACHE;
    sc_out< sc_lv<3> > m_axi_fb_ARPROT;
    sc_out< sc_lv<4> > m_axi_fb_ARQOS;
    sc_out< sc_lv<4> > m_axi_fb_ARREGION;
    sc_out< sc_lv<1> > m_axi_fb_ARUSER;
    sc_in< sc_logic > m_axi_fb_RVALID;
    sc_out< sc_logic > m_axi_fb_RREADY;
    sc_in< sc_lv<8> > m_axi_fb_RDATA;
    sc_in< sc_logic > m_axi_fb_RLAST;
    sc_in< sc_lv<1> > m_axi_fb_RID;
    sc_in< sc_lv<1> > m_axi_fb_RUSER;
    sc_in< sc_lv<2> > m_axi_fb_RRESP;
    sc_in< sc_logic > m_axi_fb_BVALID;
    sc_out< sc_logic > m_axi_fb_BREADY;
    sc_in< sc_lv<2> > m_axi_fb_BRESP;
    sc_in< sc_lv<1> > m_axi_fb_BID;
    sc_in< sc_lv<1> > m_axi_fb_BUSER;
    sc_in< sc_lv<32> > fb_offset;


    // Module declarations
    Mat2Array(sc_module_name name);
    SC_HAS_PROCESS(Mat2Array);

    ~Mat2Array();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > img_data_stream_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > exitcond_reg_234;
    sc_signal< sc_logic > fb_blk_n_AW;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > fb_blk_n_W;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > exitcond_reg_234_pp0_iter1_reg;
    sc_signal< sc_logic > fb_blk_n_B;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<11> > t_V_1_reg_131;
    sc_signal< sc_lv<33> > sext_cast_fu_142_p1;
    sc_signal< sc_lv<33> > sext_cast_reg_215;
    sc_signal< sc_lv<11> > row_V_fu_152_p2;
    sc_signal< sc_lv<11> > row_V_reg_223;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > fb_addr_reg_228;
    sc_signal< sc_lv<1> > exitcond1_fu_146_p2;
    sc_signal< sc_lv<1> > exitcond_fu_203_p2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter2;
    sc_signal< sc_logic > ap_sig_ioackin_m_axi_fb_WREADY;
    sc_signal< bool > ap_block_state6_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<11> > col_V_fu_209_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<8> > tmp_3_reg_243;
    sc_signal< sc_logic > ap_sig_ioackin_m_axi_fb_AWREADY;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state4;
    sc_signal< sc_lv<11> > t_V_reg_120;
    sc_signal< sc_lv<64> > sum1_cast_fu_193_p1;
    sc_signal< sc_logic > ap_reg_ioackin_m_axi_fb_AWREADY;
    sc_signal< sc_logic > ap_reg_ioackin_m_axi_fb_WREADY;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<18> > p_shl2_fu_166_p3;
    sc_signal< sc_lv<22> > p_shl_fu_158_p3;
    sc_signal< sc_lv<22> > p_shl2_cast_fu_174_p1;
    sc_signal< sc_lv<22> > ret_V_fu_178_p2;
    sc_signal< sc_lv<33> > tmp_6_cast_fu_184_p1;
    sc_signal< sc_lv<33> > sum1_fu_188_p2;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_fsm_state1;
    static const sc_lv<9> ap_ST_fsm_state2;
    static const sc_lv<9> ap_ST_fsm_state3;
    static const sc_lv<9> ap_ST_fsm_pp0_stage0;
    static const sc_lv<9> ap_ST_fsm_state7;
    static const sc_lv<9> ap_ST_fsm_state8;
    static const sc_lv<9> ap_ST_fsm_state9;
    static const sc_lv<9> ap_ST_fsm_state10;
    static const sc_lv<9> ap_ST_fsm_state11;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<32> ap_const_lv32_780;
    static const sc_lv<11> ap_const_lv11_438;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<11> ap_const_lv11_780;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state4_pp0_stage0_iter0();
    void thread_ap_block_state5_pp0_stage0_iter1();
    void thread_ap_block_state6_io();
    void thread_ap_block_state6_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state4();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_ap_sig_ioackin_m_axi_fb_AWREADY();
    void thread_ap_sig_ioackin_m_axi_fb_WREADY();
    void thread_col_V_fu_209_p2();
    void thread_exitcond1_fu_146_p2();
    void thread_exitcond_fu_203_p2();
    void thread_fb_blk_n_AW();
    void thread_fb_blk_n_B();
    void thread_fb_blk_n_W();
    void thread_img_data_stream_V_blk_n();
    void thread_img_data_stream_V_read();
    void thread_m_axi_fb_ARADDR();
    void thread_m_axi_fb_ARBURST();
    void thread_m_axi_fb_ARCACHE();
    void thread_m_axi_fb_ARID();
    void thread_m_axi_fb_ARLEN();
    void thread_m_axi_fb_ARLOCK();
    void thread_m_axi_fb_ARPROT();
    void thread_m_axi_fb_ARQOS();
    void thread_m_axi_fb_ARREGION();
    void thread_m_axi_fb_ARSIZE();
    void thread_m_axi_fb_ARUSER();
    void thread_m_axi_fb_ARVALID();
    void thread_m_axi_fb_AWADDR();
    void thread_m_axi_fb_AWBURST();
    void thread_m_axi_fb_AWCACHE();
    void thread_m_axi_fb_AWID();
    void thread_m_axi_fb_AWLEN();
    void thread_m_axi_fb_AWLOCK();
    void thread_m_axi_fb_AWPROT();
    void thread_m_axi_fb_AWQOS();
    void thread_m_axi_fb_AWREGION();
    void thread_m_axi_fb_AWSIZE();
    void thread_m_axi_fb_AWUSER();
    void thread_m_axi_fb_AWVALID();
    void thread_m_axi_fb_BREADY();
    void thread_m_axi_fb_RREADY();
    void thread_m_axi_fb_WDATA();
    void thread_m_axi_fb_WID();
    void thread_m_axi_fb_WLAST();
    void thread_m_axi_fb_WSTRB();
    void thread_m_axi_fb_WUSER();
    void thread_m_axi_fb_WVALID();
    void thread_p_shl2_cast_fu_174_p1();
    void thread_p_shl2_fu_166_p3();
    void thread_p_shl_fu_158_p3();
    void thread_ret_V_fu_178_p2();
    void thread_row_V_fu_152_p2();
    void thread_sext_cast_fu_142_p1();
    void thread_sum1_cast_fu_193_p1();
    void thread_sum1_fu_188_p2();
    void thread_tmp_6_cast_fu_184_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
